### ISSUE TITLE
error in ICG_normXCorr2

### ISSUE THREAD

**Issue by guillermogb** [VLOGroup/dvs-calibration#1]
@reini1305 
Hi Christian,

During Matlab execution (Matlab R2017a on Ubuntu 16.04)
>> do_calibration

I get the following error:
Warning: Name is nonexistent or not a directory: ICG_functions 
> In path (line 109)
  In addpath (line 88)
  In make_target (line 3)
  In do_calibration (line 28) 
Loading image 1...2...3...4...5...6...7...8...9...10...11...12...13...14...15...16...17...18...19...20...
done
Processing image 1/20Finding Marker...DONE. Similarity: 0.945241
Initial corner guess Invalid MEX-file 'dvs-calibration/camera_calibration/ICG_functions/private/normxcorr2_mex.mexa64':
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm' required by
'/usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4-> dvs-calibration/camera_calibration/ICG_functions/private/normxcorr2_mex.mexa64'
(...)
Error in ICG_normXCorr2 (line 45)
result = normxcorr2_mex(template, image, shape);
Error in ICG_initialCornerGuess>calcOffset (line 371)
corr_image = abs(ICG_normXCorr2(template, search_window, 'valid'));
Error in ICG_initialCornerGuess>refinePoints (line 341)
    [offset_cr, similarity, contrast] = calcOffset (refinePoints_template, warped_image);
Error in ICG_initialCornerGuess (line 102)
[image_points_x, image_points_y, feature_mask_valid, feature_mask_failed] = refinePoints(point_indices(:,17:end), ...
Error in ICG_extractCornersLoop (line 47)
[corner_guess, grid_coord] = ICG_initialCornerGuess (current_image, marker_corners, parameters.target_type, feature_x_grid, feature_y_grid,
parameters.verbose);
Error in auto_calib (line 41)
    [active_images(i), corner_points{i}, grid_coords{i}] = ICG_extractCornersLoop (image_stack{i}, template_pattern, parameters, localverbose_info,i);
Error in do_calibration (line 113)
auto_calib;
 
I searched the [solution online](https://github.com/vlfeat/matconvnet/issues/937) and it seems that one has to execute the following command before loading matlab on the same shell:
```export LD_PRELOAD=$LD_PRELOAD:/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/usr/lib/x86_64-linux-gnu/libprotobuf.so.9```

Just in case you want to know or you want to add to the Readme.md

Best,
Guillermo

**Comment by reini1305** [comment]
Hi Guillermo,

yes, I will add this to the README.md. I've done this modification years ago and totally forgot about it. Thanks for pointing this out!
