### ISSUE TITLE
grabber building errors

### ISSUE THREAD

**Issue by Thanh-Binh** [VLOGroup/dvs-calibration#2]
today I have got the following error after executing 
make
Do you have any idea? Thanks

#################################
/usr/include/libcaer/events/special.h: In function ‘caer_special_event* caerSpecialEventPacketFindValidEventByType(caerSpecialEventPacket, int)’:
/usr/include/libcaer/events/special.h:499:57: error: ‘caerSpecialEventGetType’ was not declared in this scope
   if (caerSpecialEventGetType(caerSpecialIteratorElement) == type) {
                                                         ^
/usr/include/libcaer/events/special.h: At global scope:
/usr/include/libcaer/events/special.h:520:121: error: ‘uint8_t’ has not been declared
 PacketFindValidEventByTypeConst(caerSpecialEventPacketConst packet, uint8_t typ
                                                                     ^
/usr/include/libcaer/events/special.h: In function ‘const caer_special_event* caerSpecialEventPacketFindValidEventByTypeConst(caerSpecialEventPacketConst, int)’:
/usr/include/libcaer/events/special.h:522:57: error: ‘caerSpecialEventGetType’ was not declared in this scope
   if (caerSpecialEventGetType(caerSpecialIteratorElement) == type) {
                                                         ^
In file included from /home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp:19:0:
/usr/include/libcaer/devices/dvs128.h: At global scope:
/usr/include/libcaer/devices/dvs128.h:138:2: error: ‘uint8_t’ does not name a type
  uint8_t deviceUSBBusNumber;
  ^
/usr/include/libcaer/devices/dvs128.h:140:2: error: ‘uint8_t’ does not name a type
  uint8_t deviceUSBDeviceAddress;
  ^
/home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp: In function ‘int main()’:
/home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp:32:70: error: ‘caerDeviceOpen’ cannot be used as a function
     dvs128_handle_ = caerDeviceOpen(1, CAER_DEVICE_DVS128, 0, 0, NULL);
                                                                      ^
/home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp:104:80: error: ‘caerPolarityEventGetX’ was not declared in this scope
          event.x = caerPolarityEventGetX(caerPolarityIteratorElement); // don't
                                                                     ^
/home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp:105:80: error: ‘caerPolarityEventGetY’ was not declared in this scope
                   event.y = caerPolarityEventGetY(caerPolarityIteratorElement);

**Comment by reini1305** [comment]
Which version of libcaer have you used? I've included one here as submodule which is supposed to work.

**Comment by Thanh-Binh** [comment]
I think the newest version

**Comment by reini1305** [comment]
Don't use that. Please follow the compilation instructions closely...

**Comment by Thanh-Binh** [comment]
Do not understand because the libcaer was yesterday installed by sudo at pano-tracking? I followed it exactly!

**Comment by reini1305** [comment]
Did you do the recursive git checkout? This pulls a specific version of libcaer

**Comment by Thanh-Binh** [comment]
Today morning, I checkout git with recursive, and I did 100% exactly installation in your document. I have got the following errors:
binh@volkswagen:~/Neuromorphics/dvs-calibration/grabber/build$ make
Scanning dependencies of target grabber
[ 33%] Building CXX object CMakeFiles/grabber.dir/grabber.o
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /usr/local/include/libcaer/libcaer.h:20,
                 from /home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp:18:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/local/include/libcaer/libcaer.h:42:0,
                 from /home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp:18:
/usr/local/include/libcaer/log.h:62:22: error: variable or field ‘caerLogLevelSet’ declared void
 void caerLogLevelSet(uint8_t logLevel);
                      ^
/usr/local/include/libcaer/log.h:62:22: error: ‘uint8_t’ was not declared in this scope
/usr/local/include/libcaer/log.h:71:1: error: ‘uint8_t’ does not name a type
 uint8_t caerLogLevelGet(void);
 ^
/usr/local/include/libcaer/log.h:98:14: error: variable or field ‘caerLog’ declared void
 void caerLog(uint8_t logLevel, const char *subSystem, const char *format, ...) 
              ^
/usr/local/include/libcaer/log.h:98:14: error: ‘uint8_t’ was not declared in this scope
/usr/local/include/libcaer/log.h:98:32: error: expected primary-expression before ‘const’
 void caerLog(uint8_t logLevel, const char *subSystem, const char *format, ...) 
                                ^
/usr/local/include/libcaer/log.h:98:55: error: expected primary-expression before ‘const’
 void caerLog(uint8_t logLevel, const char *subSystem, const char *format, ...) 
                                                       ^
/usr/local/include/libcaer/log.h:98:75: error: expected primary-expression before ‘...’ token
 aerLog(uint8_t logLevel, const char *subSystem, const char *format, ...) ATTRIB
                                                                     ^
In file included from /home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp:18:0:
/usr/local/include/libcaer/libcaer.h:181:43: error: variable or field ‘caerIntegerToByteArray’ declared void
 static inline void caerIntegerToByteArray(uint32_t integer, uint8_t *byteArray,
                                           ^
/usr/local/include/libcaer/libcaer.h:181:43: error: ‘uint32_t’ was not declared in this scope
/usr/local/include/libcaer/libcaer.h:181:61: error: ‘uint8_t’ was not declared in this scope
 static inline void caerIntegerToByteArray(uint32_t integer, uint8_t *byteArray,
                                                             ^
/usr/local/include/libcaer/libcaer.h:181:70: error: ‘byteArray’ was not declared in this scope
 tatic inline void caerIntegerToByteArray(uint32_t integer, uint8_t *byteArray, 
                                                                     ^
/usr/local/include/libcaer/libcaer.h:181:81: error: ‘uint8_t’ was not declared in this scope
 e void caerIntegerToByteArray(uint32_t integer, uint8_t *byteArray, uint8_t byt
                                                                     ^
In file included from /usr/include/c++/5/new:40:0,
                 from /usr/include/c++/5/ext/new_allocator.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/vector:61,
                 from /home/binh/Neuromorphics/dvs-calibration/grabber/grabber.cpp:20:
/usr/include/c++/5/exception:35:37: error: expected ‘}’ before end of line
/usr/include/c++/5/exception:35:37: error: expected declaration before end of line
CMakeFiles/grabber.dir/build.make:62: recipe for target 'CMakeFiles/grabber.dir/grabber.o' failed
make[2]: *** [CMakeFiles/grabber.dir/grabber.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/grabber.dir/all' failed
make[1]: *** [CMakeFiles/grabber.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by reini1305** [comment]
Ok, I can't check right now because I'm traveling. Can you compile the libcaer of panotracking again? This should also work with this repo.

**Comment by Thanh-Binh** [comment]
If you want to use a special version, you have to modify CMakefile.txt accordingly, so that it should not need sudo make install. Other words, you have to install libcaer and link LOCALLY!

**Comment by reini1305** [comment]
It seems if I made a mistake and linked to the wrong commit of libcaer. They like to change the api constantly which is a bit of a pain. Will correct it when I'm back home.

**Comment by Thanh-Binh** [comment]
Thanks
